### ISSUE TITLE
Error messages when importing

### ISSUE THREAD

**Issue by LollerMann** [lewa-j/Unity-Source-Tools#1]
Can you update the code?
I made a blank project then directly imported it, Unity warned me that it was obsolete but i proceed, then unity came up with two error messages.
`Shader error in 'WorldVertexTransition': undeclared identifier 'mix' at line 30 (on d3d11)

Compiling Vertex program with DIRECTIONAL
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME
`
`Assets/Code/Read/SourceBSPLoader.cs(574,138): error CS0170: Use of possibly unassigned field `texdata'
`
Unity version: 5.6.3f1 personal 64 bit
Thank you.

**Comment by lewa-j** [comment]
The code has not been updated since Unity 4.7, so much needs work. I do not plan to work on this project anymore. You can use Unity 4.7 or find someone who can rewrite the code for the new version.

**Comment by StamatisP** [comment]
The texdata error is fixed by adding in the lines
 `face = map.facesLump[i];

ti = map.texinfosLump[face.texinfo];` 
On lines 574 and 575. 
For the shader error, I just commented it out since I don't understand shaders at all.

Though after I got through that, I don't even know how to use the tools anyway.

**Comment by StamatisP** [comment]
Update, I have messed around with the code and settings to get it to work(and added some small but well needed documentation) and it is now almost successfully generating the map. 
![jrnb90h 1](https://user-images.githubusercontent.com/9277442/43691527-dbf1253a-98eb-11e8-8aa9-6bc0cb1cb9db.png)

My only problem now is exporting, as COLLADA is asking for the second value in the mesh.sources array, when there is only one. If I fix this problem, I'll do a pull request to keep this updated. However, I don't see myself fixing this easily, as I have no idea how this export stuff works yet.

By the way, I am on 2018.2.1f1.

**Comment by StamatisP** [comment]
I fixed the export map function, I think! I'll clean up my space and issue a pull request.
