### ISSUE TITLE
Half-Life 2 Beta BSP(v18) Array index error despite the map data loading

### ISSUE THREAD

**Issue by Fronkln** [lewa-j/Unity-Source-Tools#10]
`ti = map.texinfosLump[face.texinfo];`

This line generates an array index out of range error even though map data has been loaded perfectly.

Load: 501 TextureData's 
Load: 16544 Vertexes 
Load: 5602 TexInfos 
Load: 11773 Faces 
Load :45263 Edges 
Load :72666 SurfEdges 
Load: 86 Models 
Load: 43 DispInfos 
Load: 3019 DispVerts 
Load: 3 GameLumps 
Load :48153 TexDataStringData 
Load :876 TexDataStringsTable 

The error happens when it starts loading the faces.

![image](https://user-images.githubusercontent.com/17107072/57853008-59429100-77ed-11e9-95d7-aed5f1a626f2.png)

Map's texinfo seems to be loaded.

**Comment by lewa-j** [comment]
v18 face struct has additional 16 bytes in the beginning.

**Comment by Fronkln** [comment]
> v18 face struct has additional 16 bytes in the beginning.

And is there any way to edit the code so it loads these 16 bytes? I'm afraid im not that knowledged in these type of stuff

**Comment by lewa-j** [comment]
Just commited. Try it now

**Comment by Fronkln** [comment]
> Just commited. Try it now

Works perfectly, thank you!

![image](https://user-images.githubusercontent.com/17107072/57861571-7c763c00-77ff-11e9-9881-fcc3ab6b0906.png)

**Comment by Fronkln** [comment]
Another quick question, is there a way to force nodraws to load in v19 and above? they simply do not load but i need them for NPC navigation because certain maps have the NPC's walk in invisible terrain
