### ISSUE TITLE
Distrubute on Steam Exception

### ISSUE THREAD

**Issue by ninjafootball07** [lewa-j/Unity-Source-Tools#14]
I noticed the license is GPLv2, do you allow exceptions for devs creating games for Steam that want to include the tools in their Source SDK depots?

Looking for a HL1/Source SDK license.

**Comment by nekonomicon** [comment]
It's illegal to link source code under GPL and valve's EULA.
But this project for Unity and does not have code parts from Source SDK.
So you can distribute this tools without restrictions.
