### ISSUE TITLE
Lightmaps reset if the map was loaded in editor mode

### ISSUE THREAD

**Issue by Fronkln** [lewa-j/Unity-Source-Tools#18]
Self explanatory, if the map was loaded from editor with the "Load" button the generated lightmap texture will disappear on play mode

**Comment by antim0118** [comment]
Yeah, its unity bug. It will always reset if shadows wasn't baked by unity.
Solution: import lightmap to jpg/png/exr and apply it using "LightmapSettings" through script.

**Comment by Fronkln** [comment]
> Yeah, its unity bug. It will always reset if shadows wasn't baked by unity.
> Solution: import lightmap to jpg/png/exr and apply it using "LightmapSettings" through script.

I converted it into a png image and loaded it today but it still wouldnt apply even though its at baked lightmaps list
 probably something specific needs to be done before it works properly

![SavedScreen](https://user-images.githubusercontent.com/17107072/57982972-0f5be400-7a55-11e9-90a2-e897b92dc2b8.png)

The lightmap image that i used (city_test09.bsp)

**Comment by antim0118** [comment]
I created this script to apply them.
https://pastebin.com/sfmLsL4f
I hope it will work.

**Comment by Fronkln** [comment]
> I created this script to apply them.
> https://pastebin.com/sfmLsL4f
> I hope it will work.

Works perfectly, perhaps we should start integrating this into bsp loading itself that works when the app starts?
