### ISSUE TITLE
Textures sometimes will not be loaded in Editor

### ISSUE THREAD

**Issue by Fronkln** [lewa-j/Unity-Source-Tools#19]

**Comment by antim0118** [comment]
Console warnings?

**Comment by Fronkln** [comment]
> Console warnings?

Absolutely not, 0

**Comment by antim0118** [comment]
Hmm... Give me link to hl2beta (you trying to load it as i can see) and mapname, i will try to load it

**Comment by Fronkln** [comment]
> Hmm... Give me link to hl2beta (you trying to load it as i can see) and mapname, i will try to load it

https://hl2-beta.ru/index.php?action=downloads;sa=view;down=245

you will need to be registered, i'm loading city_test_09 from "fanmade_fixes" mod so basically you should configure it like this

Game: hl2
mod: fanmade_fixes
map: city_test_09

**Comment by Fronkln** [comment]
Additionally if you ever need to talk or ask a few questions you can add me on steam with the username Jhrino

**Comment by antim0118** [comment]
> you will need to be registered, i'm loading city_test_09 from "fanmade_fixes" mod so basically you should configure it like this

yeah i had it before

**Comment by antim0118** [comment]
hmm... i dont have any problems. only 2 models missing.
maybe fixed in last commits
![Screenshot](https://pp.userapi.com/c850732/v850732299/11ed80/w4Ynmzmxei8.jpg)

**Comment by Fronkln** [comment]
> hmm... i dont have any problems. only 2 models missing.
> maybe fixed in last commits
> ![Screenshot](https://camo.githubusercontent.com/ff43f3b61ed464aaf7511160ae922e6341954c94/68747470733a2f2f70702e757365726170692e636f6d2f633835303733322f763835303733323239392f3131656438302f7734596e6d7a6d786569382e6a7067)

It happens when you repeatedly delete the loaded map and load it again,i was also playing with lighting settings when this bug happened so try turning off baked and realtime lights and try to load map repeatedly

**Comment by antim0118** [comment]
I dont see this bug, but i found [a new one](https://github.com/lewa-j/Unity-Source-Tools/pull/23)

**Comment by Fronkln** [comment]
Then its super likely you have fixed it in your commits, i'll take a look

**Comment by antim0118** [comment]
oh, i figured out how this bug works. i think you were trying to load a map when unity tried to load scripts and it reseted all textures.
solution: wait for unity then load map. if you have this bug, restart unity (or update/save scripts to let unity reupdate them).
![image](https://user-images.githubusercontent.com/22983870/57987023-7a2d0f80-7a95-11e9-95de-577bc9013579.png)
