### ISSUE TITLE
(Question) Source Entities with Functionality

### ISSUE THREAD

**Issue by Fronkln** [lewa-j/Unity-Source-Tools#21]
Do we plan to add support for Source entity functionality as well? What i mean by that is stuff like trigger_once actually doing something instead of being just loaded without any functionality, i have quite a few of them coded in my project and was wondering if it was okay to commit them here

**Comment by Fronkln** [comment]
![image](https://user-images.githubusercontent.com/17107072/57983749-0cb1bc80-7a5e-11e9-9f1e-2b6cf7831c24.png)

Example entity implementation

**Comment by lewa-j** [comment]
I was not going to do that.
