### ISSUE TITLE
Incorrect Rotation for Skybox Textures

### ISSUE THREAD

**Issue by Fronkln** [lewa-j/Unity-Source-Tools#26]
Just making an "issue" for this so this get's more attention, on my skybox loading code, due to how Source handles skybox textures, the up texture of skybox will have incorrect rotation and will not match with the rest of the skybox.

The solution is simple:

Rotate the Skybox Up Texture2D by 90 degrees clockwise

The issue:
I do not know how to do this

So if any of you coders out there can do this it would greatly help loading Skyboxes from the game

**Comment by antim0118** [comment]
Have you tried [this](https://answers.unity.com/questions/951835/rotate-the-contents-of-a-texture.html) ?

**Comment by Fronkln** [comment]
@antimYT It's giving not intended results

Default image

![image](https://user-images.githubusercontent.com/17107072/58909757-8ca57b00-871c-11e9-9478-5eff7d71f37a.png)

Rotate Matrix
![image](https://user-images.githubusercontent.com/17107072/58909792-aba40d00-871c-11e9-8730-803a8e594b76.png)

What we actually need to do so it works

![image](https://user-images.githubusercontent.com/17107072/58909815-b78fcf00-871c-11e9-9799-0907d6e30ec9.png)

**Comment by Fronkln** [comment]
IMPORTANT DISCOVERY!

All textures excluding UP has to be FLIPPED which can be done with Array.Reverse

**Comment by antim0118** [comment]
> It's giving not intended results

works for me.
![skyboxgh](https://user-images.githubusercontent.com/22983870/61578449-7c046500-ab10-11e9-9709-41c5620bd68f.png)

i had to write my own code so here it is (im too lazy to pull request it)
```
if (uSrcSettings.Inst.skyBox)
{
    Material skybox = new Material(Shader.Find("Skybox/6 Sided"));

    string[] skysides = new string[] { "bk", "ft",  "rt", "lf", "up", "dn" };
    string[] skysides_u = new string[] { "_FrontTex", "_BackTex", "_LeftTex", "_RightTex", "_UpTex", "_DownTex" };

    for (int side = 0; side < 6; side++) {
        var tex = ResourceManager.Inst.GetTexture($"skybox/{skyName}{skysides[side]}").ToTexture2D();
        ConvertUtils.FlipTextureVertically(tex);
        if (side >= 4)
            tex = tex.rotateTexture(false);
        tex.wrapMode = TextureWrapMode.Clamp;
        skybox.SetTexture(skysides_u[side], tex);
    }
    RenderSettings.skybox = skybox;
    DynamicGI.UpdateEnvironment();
}
```
And functions for ConvertUtils.cs: https://pastebin.com/WvR6DKsJ

**Comment by Fronkln** [comment]
Noted
