### ISSUE TITLE
Material Load issue

### ISSUE THREAD

**Issue by greyyzilla** [lewa-j/Unity-Source-Tools#27]
![image](https://user-images.githubusercontent.com/52096364/59960833-d806aa00-94ce-11e9-8dad-4601c96d582e.png)

Loading maps from Gmod with CSS content addons doesn't seem to load textures and or props well.

**Comment by Fronkln** [comment]
It's because uSrc does not look at the Addons folder of Garry's Mod. Try setting asset path to the folder of css content.

**Comment by antim0118** [comment]
Have you enabled texture checkbox?

upd: maybe textures and models are included in bsp file, try to extract them

**Comment by Fronkln** [comment]
> Have you enabled texture checkbox?
> 
> upd: maybe textures and models are included in bsp file, try to extract them

Nah, i'm pretty sure they are using CSS content in a folder located in Garry's Mod/garrysmod/addons which uSrc does not look at by default unless they set it as asset path

**Comment by greyyzilla** [comment]
![image](https://user-images.githubusercontent.com/52096364/59960908-118be500-94d0-11e9-8872-d49a14b9628d.png)
Kinda fixed aside from the main ground texture being nonexistent. BSP is probably needed to extract.

**Comment by Fronkln** [comment]
Can you check the warnings part of Unity console so we can see what texture is missing?

**Comment by greyyzilla** [comment]
![image](https://user-images.githubusercontent.com/52096364/59960933-5879da80-94d0-11e9-99c0-a839c74586f6.png)
Seems to be missing a lot of "cobble" textures, I'm guessing BSP extraction and paste its contents to the Content Addon file will fix it right away?

**Comment by Fronkln** [comment]
Absolutely

**Comment by Fronkln** [comment]
It's referencing materials packed into the BSP, which we kinda wrote code for v18 to prevent but CS:S is 20

**Comment by Fronkln** [comment]
Open the map with GCFScape, extract materials folder to Garry's Mod/garrysmod

**Comment by greyyzilla** [comment]
![image](https://user-images.githubusercontent.com/52096364/59960989-464c6c00-94d1-11e9-84d6-fe0e52c56c4d.png)
I used BSPSrc, extracted the materials to the mentioned folder by the Unity Console and it works, thanks!

**Comment by Fronkln** [comment]
Close the issue now that it's solved.
