### ISSUE TITLE
all entities dont load

### ISSUE THREAD

**Issue by CL3NRc** [lewa-j/Unity-Source-Tools#36]
every single map i try to load doesnt load all of the entities and props in the map. instead it only loads a few, and most of that few has a blank grey texture

**Comment by CL3NRc** [comment]
someone, anyone, PLEASE HELP ME!!! im losing my shit trying to get this damn plugin to work!

**Comment by CL3NRc** [comment]
im starting to think that this plugin is fake... or maybe even broken, but no-one cares enough to say anything...

**Comment by lewa-j** [comment]
Not enough info. What game? What map? Which objects are missing? Did you extracted all the needed resources?

**Comment by CL3NRc** [comment]
> Not enough info. What game? What map? Which objects are missing? Did you extracted all the needed resources?

im trying to extract a garry's mod workshop map, its a five nights at freddy's 1 map, but it doesnt seem to want to work right. most objects like pirates cove, balloons, the cloth on the tables, children drawings, office props like the fan and tv's, all of that stuff isnt loading. the only things that loaded are the base tables, untextured chairs, some doors, the office lamp, 1 shelf, and the office desk.

**Comment by CL3NRc** [comment]
is there a specific version of unity i need or something?

**Comment by CL3NRc** [comment]
also, what do you mean by extracted? you never said anything about extracting props from a map in the read me

**Comment by CL3NRc** [comment]
i've tried everything... it just will not load the props. i mean, at random it will load way more props than before, but i have no idea how to get it to do that constantly

**Comment by antim0118** [comment]
1. uSrcTools can't read Gmod addons.
2. You need to extract PAK file (sometimes it contains textures/models) included to BSP file (using Pakrat)

**Comment by CL3NRc** [comment]
well what the hell is the point of using this tool if when i use a workshop bsp file it doesnt work right! the workshop has soo many possibilities with maps, and the only bsp files i can properly extract is only 2 default maps? what a waste of time

**Comment by CL3NRc** [comment]
i literally extracted the bsp, models and textures from the gmod gma file, and your telling me that because its a workshop item that it doesnt work right? what the hell is the point of having garry's mod as an option if the only two official gmod maps are construct and flatgrass?

**Comment by antim0118** [comment]
Dude.
I specifically made "assets path" to fix that problem. You should extract vpk/bsp pak/gma's to this folder.
Also you can check console for errors/warnings.

It works exactly the same with csgo/l4d2/hl2.

**Comment by CL3NRc** [comment]
yeah, moving everything to the assets path didn't change a thing. there's still not every entity that's supposed to be there.

**Comment by CL3NRc** [comment]
and the only thing that's giving me errors are just a few textures that has nothing to do with the actual props

**Comment by antim0118** [comment]
give me link to this map, i will check it

**Comment by Fronkln** [comment]
entities that uSrc can load are in the testEnts array in SourceBSPLoader.cs

**Comment by CL3NRc** [comment]
> entities that uSrc can load are in the testEnts array in SourceBSPLoader.cs

yeah, good luck getting me to use that broken thing. it keeps saying "model isnt loaded" and it just gives me an empty game object called test model

**Comment by Fronkln** [comment]
![image](https://user-images.githubusercontent.com/17107072/66200884-b363c600-e6aa-11e9-930e-2fc0e9df0d59.png)

surely if this thing was broken i wouldn't be able to achieve this?

**Comment by antim0118** [comment]
this guy doesn't knows what he should do to make it work😕
