### ISSUE TITLE
For some of the models the script looks in the wrong place for the .vmf file and adds some numbers to the .vmf that it is looking for.

### ISSUE THREAD

**Issue by ghost** [lewa-j/Unity-Source-Tools#4]
![texturehelp1](https://user-images.githubusercontent.com/12180913/48754565-fae19d80-ecf6-11e8-9cea-0aeb7f308381.PNG)

![texturehelp2](https://user-images.githubusercontent.com/12180913/48754600-19e02f80-ecf7-11e8-86b3-25f12039fff2.PNG)

These are the pictures of the list of files it is lookings for and where they acutaly are. The second image is my settings to make sure everything is configures correctly.

Looking forward to your help. :+1:

**Comment by StamatisP** [comment]
This is done because of how Source handles cubemaps for reflections, I believe. It's a pain, but what I did was copy/paste the original file, and rename it to fit.

**Comment by lewa-j** [comment]
These files are in a zip inside the bsp file. You should unpack them with GCFScape.

**Comment by ghost** [comment]
Thank you. Got it working but some of the models are still missing and the clock is mis placed.
![texturehelp4](https://user-images.githubusercontent.com/12180913/48800425-995d1580-ed6e-11e8-9dbd-3e36d76ec409.PNG)

**Comment by StamatisP** [comment]
You still haven't filled out all of the materials in the WorldManager. That's the cause of the source argument error. Try that out.

**Comment by ghost** [comment]
What materials are that? Where are they on the world manager menu?

**Comment by ghost** [comment]
List of models the are visible:
Bed
Walls
Doors
Center of Button
Cube dropper

Non visible or not there:
Auto portal frame
mini stone table
check board
radio
button holder/outer
circuit line from button to door
all parts of the elevator

Objects you can walk through:
Doors
"Glass" if it is there is has no refraction effect so it is invisible

Glitchy stuff:
Countdown clock is on the wrong wall and misaligned.

**Comment by ghost** [comment]
Fixed some of the problems by setting the transparent cut out. What do I set the vertex lit material to?

**Comment by lewa-j** [comment]
Diffuse

**Comment by atrblizzard** [comment]
> 
> 
> These files are in a zip inside the bsp file. You should unpack them with GCFScape.

I've commited a pull request to fix this issue, removing this step altogether.

**Comment by lewa-j** [comment]
#5 
This is just a workaround. As a result, we lose all the information about cubemaps. The right solution to the problem is to make loading materials from the zip archive from bsp.

**Comment by ghost** [comment]
Fixxed almost all of the problems now!!
1. The test chamber sign is improperly displayed
2. The clock holder is misaligned

3. When I click stop play it removes the map. How can I stop this so I can edit it such as adding physics to objects etc?

How can I fix these?

Picture one is bad sign and misaligned clock
![texturehelp6](https://user-images.githubusercontent.com/12180913/48880574-060f0780-ee76-11e8-81c6-2cdf2addff12.PNG)

Picture two is configuration and debug console
![texturehelp7](https://user-images.githubusercontent.com/12180913/48880608-23dc6c80-ee76-11e8-865f-87c33b9393a5.PNG)

**Comment by ghost** [comment]
Extra problem:
I can still walk through most 3d models such as the doors and elevator.

**Comment by lewa-j** [comment]
1. Testchamber Signs are complex (https://developer.valvesoftware.com/wiki/Custom_Testchamber_Signs)
2. MDL loader is unfinished. Can on some files fail root bone rotation.
3. Script creates all meshes and objects in runtime and stores them only in RAM. For editing, they must first be exported. Started writing collada exporter, but doesn't finish.
4. Same to 2nd, mdl loader doesn't load collision files.

**Comment by ghost** [comment]
How much of the exporter is done and how long do you think it will take? I would like to be able to use it by Christmas.

**Comment by lewa-j** [comment]
Done only vertices and UVs, without materials and objects.

> how long do you think it will take

Well, forever. It was abandoned almost two years ago.

**Comment by ghost** [comment]
Well damn. Is there a way you could edit the script loader so it adds the objects as permanent objects? Like loading the materials and models into a permanent folder(PortalProject/Objects). Or what if I got you like 10 professions to assist you with finishing the exporter?

**Comment by StamatisP** [comment]
Throwing people at it would certainly help (provided they're paid well), but it's not really worth it. I suggest recreating it in probuilder, because the way Source does maps is really wonky compared to Unity.

**Comment by ghost** [comment]
Check this out. https://www.reddit.com/r/Unity3D/comments/a0dy17/can_we_get_some_people_to_help_with_a_project/?

Also what do you think of my first recommendation?

**Comment by StamatisP** [comment]
Those aren't really experts, I doubt someone in their spare time would work on a project like this without any monetary incentive. I'm sorry, but your best choice is to rebuild the map completely. Otherwise, shadows and such are broken.

**Comment by ghost** [comment]
Damn. Tbh I don't really care if shadows are broken.

**Comment by ghost** [comment]
Update. I can easily fix the non existent colliers by just clicking add mesh collier(It even automatically picks the mesh to use!) Also just saying its probably easier to just change the code so it loads the materials and props to a permanent location than finishing the export script.

**Comment by lewa-j** [comment]
> 
> 
> it's not really worth it. I suggest recreating it in probuilder, because the way Source does maps is really wonky compared to Unity.

Kevin43 is right.

**Comment by StamatisP** [comment]
I wish there was a way to do that Footsie, but I don't think it's very possible. Correct me if I'm wrong lewaj, but the objects created with this script were never meant to be permanent, right? They work in really weird ways(all transforms are at 0) that I don't fully understand.

**Comment by lewa-j** [comment]
This was intended as a script that loads the entire level in runtime from the original files from Source. So editing in Unity would not be necessary. That is, everything was done only through the code, almost without an editor.

**Comment by ghost** [comment]
Well damn. Im sad. [https://www.youtube.com/watch?v=6e9JhE9miOg](https://www.youtube.com/watch?v=6e9JhE9miOg) I believe someone used to plugin to partly make what my project is. Except I want to convert all of the portal maps. Any idea how he might have done it?

**Comment by lewa-j** [comment]
I think he used Crafty http://nemesis.thewavelength.net/index.php?p=45
Also, did you know that the portal is already ported to android by Nvidia?

**Comment by StamatisP** [comment]
I've tested with Crafty before, but it didn't work well in my case. Porting the entire map as a model is really unperformant for me.

**Comment by ghost** [comment]
Crafty cannot export portal maps as all of the objects are rotated 90deg the wrong way and the textures are misaligned even when I rotate them.

**Comment by ghost** [comment]
here screenshot:
![crafty](https://user-images.githubusercontent.com/12180913/49061083-bb75fc80-f274-11e8-9269-aa55948eff43.PNG)

**Comment by atrblizzard** [comment]
@Footsiefat, you may try something like [VMFLoader](https://github.com/aleksijuvani/unity-vmf-loader) to import VMFs and then convert them into ProBuilder brushes.

Looks like there is an issue with loading materials and models when using mods, hence the missing content. I'll see what I can do about it, along with the regex string.

**Comment by ghost** [comment]
I tried to use that importer but once I copied the files I could not find where to go to import the map.

**Comment by ghost** [comment]
Where did you go to import the map?
