### ISSUE TITLE
Without Batching Doesn't Work

### ISSUE THREAD

**Issue by Fronkln** [lewa-j/Unity-Source-Tools#42]
Normally gives index outside the bounds of the array, so i added this line in the circle

![image](https://user-images.githubusercontent.com/17107072/89998609-75560c00-dc96-11ea-9094-d9a4f9b6b600.png)

That fixed the error, but now no mesh is built.

**Comment by Fronkln** [comment]
The issue is probably related to this for loop right here
![image](https://user-images.githubusercontent.com/17107072/89999972-39bc4180-dc98-11ea-9443-06f47099497d.png)

No errors are thrown, materials seem to get assigned to the meshes, but the built mesh is 0 vertices.

**Comment by Fronkln** [comment]
GenerateFaceObject calls BuildFace which returns a null surface.

**Comment by Fronkln** [comment]
Copy pasting GenerateFaceObject code from 2015 fixed it, commit later?

**Comment by lewa-j** [comment]
WithoutBatching mode was once used for debuging and never ment to be useful. Can be deleted altogether.

**Comment by Fronkln** [comment]
The code that once made it work is more useful than you think, i recently wrote code that made water planes not get batched so that if i ever figure out how to load nodraw on maps above version 18 it would be possible to have interactable water
