### ISSUE TITLE
prop_static version 6 will not get loaded

### ISSUE THREAD

**Issue by Fronkln** [lewa-j/Unity-Source-Tools#43]
background01 - a Half-Life 2 map, has a static prop version of 4 and a BSP version of 19. Which loads fine.

However, if you make a new map with the hammer editor that comes with HL2 (SDK 2013)
Your map's prop static version will be 6 and BSP version will be 20

The map loader will incorrectly report the amount of static props (0)

**Comment by lewa-j** [comment]
Attach bsp file please

**Comment by Fronkln** [comment]
[usrc_test.zip](https://github.com/lewa-j/Unity-Source-Tools/files/5348604/usrc_test.zip)

The two chairs are prop_static, ignore the general messiness of the map. It's a test map for entity loading

**Comment by lewa-j** [comment]
Are you sure this is the right file? I don't see any props here even in half-life 2 itself.
![usrc_test0000](https://user-images.githubusercontent.com/5416122/95482252-96856100-0996-11eb-85c6-8fb9e31049b9.jpg)

**Comment by Fronkln** [comment]
It should be the the correct map
![image](https://user-images.githubusercontent.com/17107072/95482441-c9c7f000-0996-11eb-826f-38c10e8cd4d5.png)

**Comment by Fronkln** [comment]
I even recompiled just before giving you the BSP to be sure

**Comment by lewa-j** [comment]
Give it a try in the game.

**Comment by Fronkln** [comment]
Interestingly enough they are not there - i checked the build logs twice for errors or warnings.
